### Employee API

### Create New Employee
POST {{apiGateway}}/v1/employees
Content-Type: application/json

{
  "name": "Bhuwan Prasad Upadhyay"
}

> {%
  client.global.set("employeeId", response.body['resource']['employeeId']);
%}

### Get Employee by Id
GET {{apiGateway}}/v1/employees/{{employeeId}}

### Update an Employee
PUT {{apiGateway}}/v1/employees/{{employeeId}}
Content-Type: application/json

{
  "name": "Bandana Poudyal"
}

### Get Updated Employee by Id
GET {{apiGateway}}/v1/employees/{{employeeId}}

### Delete an Employee
DELETE {{apiGateway}}/v1/employees/{{employeeId}}

### Get Deleted Employee by Id
GET {{apiGateway}}/v1/employees/{{employeeId}}

### List Employees
GET {{apiGateway}}/v1/employees


